# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('street_address_1', models.CharField(blank=True, max_length=60)),
                ('street_address_2', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('dob', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=60)),
                ('ec_phone', models.CharField(blank=True, max_length=20)),
                ('ec_email', models.EmailField(blank=True, max_length=40)),
                ('slug', models.CharField(default=people.models.make_slug, max_length=5, unique=True)),
                ('bio', models.TextField(blank=True, max_length=4000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('alt_phone', models.CharField(blank=True, max_length=20)),
                ('street_address_1', models.CharField(blank=True, max_length=60)),
                ('street_address_2', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('dob', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=60)),
                ('ec_phone', models.CharField(blank=True, max_length=20)),
                ('ec_email', models.EmailField(blank=True, max_length=40)),
                ('slug', models.CharField(default=people.models.make_slug, max_length=5, unique=True)),
                ('intake_date', models.DateField(blank=True, null=True)),
                ('WRU_ID', models.IntegerField(blank=True, null=True)),
                ('AEP_ID', models.IntegerField(default=people.models.make_AEP_ID, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
