# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='slug',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='slug',
            new_name='alias',
        ),
    ]
