# Generated by Django 5.1.2 on 2025-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperwork',
            name='eligibility_doc',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='eligibility_verified',
            field=models.BooleanField(default=False, verbose_name='Verified Eligible'),
        ),
    ]
