# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160812_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'staff'},
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='alias',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='alias',
            new_name='slug',
        ),
    ]
