# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 19:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20160817_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='US_citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[(None, 'Please Select'), ('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='marital_status',
            field=models.CharField(choices=[(None, 'Please Select'), ('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('O', 'Other')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
