# Generated by Django 5.1.2 on 2025-10-03 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_paperwork_eligibility_doc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paperwork',
            name='eligibility_doc_type',
            field=models.CharField(blank=True, choices=[('SSN', 'Social Security Number (SSN)'), ('N550', 'Form N-550'), ('N560', 'Form N-560'), ('N561', 'Form N-561'), ('N570', 'Form N-570'), ('I551', 'Form I-551'), ('I571', 'Form I-571'), ('I94', 'Form I-94'), ('ASYL', 'Asylum Approval Letter'), ('IJOR', "Immigration Judge's Order"), ('DHSL', 'DHS Letter'), ('COFA_DOC', 'Passport + I-94 (COFA Entry)')], max_length=10),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='eligibility_doc_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='eligibility_doc_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='eligibility_status',
            field=models.CharField(blank=True, choices=[('USC', 'U.S. Citizen'), ('LPR', 'Lawful Permanent Residents (Green Card Holders)'), ('ASY', 'Asylees'), ('REF', 'Refugees'), ('PAR', 'Paroled into the U.S. for at Least One Year'), ('WDR', 'Withholding of Deportation or Removal'), ('CEN', 'Conditional Entrants (Before April 1, 1980)'), ('CHE', 'Cuban or Haitian Entrants'), ('COFA', 'Citizens of the Freely Associated States')], max_length=10),
        ),
    ]
