# Generated by Django 5.1.2 on 2025-10-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_paperwork_eligibility_doc_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperwork',
            old_name='eligibility_doc_uploaded_at',
            new_name='eligibility_verified_at',
        ),
        migrations.RenameField(
            model_name='paperwork',
            old_name='eligibility_doc_uploaded_by',
            new_name='eligibility_verified_by',
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='eligibility_doc_type',
            field=models.CharField(blank=True, choices=[('SSN', 'Social Security Number (SSN)'), ('GC', 'Permanent Resident (Green Card)'), ('N550', 'Form N-550'), ('N560', 'Form N-560'), ('N561', 'Form N-561'), ('N570', 'Form N-570'), ('I551', 'Form I-551'), ('I571', 'Form I-571'), ('I94', 'Form I-94'), ('ASYL', 'Asylum Approval Letter'), ('IJOR', "Immigration Judge's Order"), ('DHSL', 'DHS Letter'), ('COFA_DOC', 'Passport + I-94 (COFA Entry)')], max_length=10),
        ),
    ]
