# Generated by Django 5.1.2 on 2025-10-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_rename_eligibility_doc_uploaded_at_paperwork_eligibility_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperwork',
            name='eligibility_doc_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Eligibility Document Expiration Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Non-Binary'), ('N', 'No Answer')], max_length=1, verbose_name='Sex'),
        ),
    ]
