# Generated by Django 5.1.2 on 2026-02-24 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_paperwork_eligibility_doc_expiration_and_more'),
        ('sections', '0003_alter_section_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_name', 'first_name'], name='people_stud_last_na_4881bb_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['intake_date'], name='people_stud_intake__1cb20f_idx'),
        ),
    ]
