# Generated by Django 5.1.2 on 2026-03-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_student_people_stud_last_na_4881bb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip Code'),
        ),
    ]
