# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20160918_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='ec_email',
            field=models.EmailField(blank=True, max_length=40, verbose_name='EC Email Address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ec_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='EC Phone Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ec_relation',
            field=models.CharField(blank=True, choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Spouse'), ('B', 'Sibling'), ('F', 'Friend'), ('G', 'Legal Guardian'), ('O', 'Other')], default='O', max_length=1, verbose_name='EC Relationship'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ec_email',
            field=models.EmailField(blank=True, max_length=40, verbose_name='EC Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ec_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='EC Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ec_relation',
            field=models.CharField(blank=True, choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Spouse'), ('B', 'Sibling'), ('F', 'Friend'), ('G', 'Legal Guardian'), ('O', 'Other')], default='O', max_length=1, verbose_name='EC Relationship'),
        ),
    ]
