# Generated by Django 5.2.16 on 2026-08-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0008_prospect_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_to', models.CharField(max_length=140, verbose_name='Release records to (person or organization)')),
                ('relationship', models.CharField(choices=[('D', 'Father'), ('M', 'Mother'), ('S', 'Spouse'), ('G', 'Legal Guardian'), ('SCH', 'School / College'), ('EMP', 'Employer'), ('AGY', 'Agency / Case Manager'), ('O', 'Other')], max_length=3, verbose_name='Relationship to student')),
                ('purpose', models.TextField(verbose_name='Purpose / records covered')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('signature', models.CharField(blank=True, max_length=140)),
                ('sig_date', models.DateField(blank=True, null=True)),
                ('guardian_signature', models.CharField(blank=True, max_length=140)),
                ('g_sig_date', models.DateField(blank=True, null=True)),
                ('release_file', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_releases_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_releases', to='people.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
