# Generated by Django 5.2.16 on 2026-09-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0008_prospect_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('released_to', models.CharField(max_length=140, verbose_name='Release records to (person or organization)')),
                ('released_to_email', models.EmailField(blank=True, max_length=40, verbose_name='Email Address')),
                ('released_to_address', models.CharField(blank=True, max_length=60, verbose_name='Address')),
                ('released_to_city', models.CharField(blank=True, max_length=30, verbose_name='City')),
                ('released_to_state', models.CharField(blank=True, max_length=2, verbose_name='State')),
                ('released_to_zip', models.CharField(blank=True, max_length=10, verbose_name='Zip Code')),
                ('attendance_records', models.BooleanField(default=False, verbose_name='Attendance records, hours, and enrollment information')),
                ('testing_information', models.BooleanField(default=False, verbose_name='Testing information and student scores')),
                ('all_information', models.BooleanField(default=False, verbose_name='All student information')),
                ('other', models.CharField(blank=True, max_length=140, verbose_name='Other')),
                ('signature', models.CharField(blank=True, max_length=140)),
                ('sig_date', models.DateField(blank=True, null=True)),
                ('guardian_signature', models.CharField(blank=True, max_length=140)),
                ('g_sig_date', models.DateField(blank=True, null=True)),
                ('release_file', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_releases_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_releases', to='people.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
