# Generated by Django 5.2.16 on 2026-09-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_recordrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordrelease',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recordrelease',
            name='revoked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
