# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20160925_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='amer_indian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='asian',
        ),
        migrations.RemoveField(
            model_name='student',
            name='black',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hispanic_latino',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pacific_islander',
        ),
        migrations.RemoveField(
            model_name='student',
            name='white',
        ),
        migrations.AddField(
            model_name='wioa',
            name='amer_indian',
            field=models.BooleanField(default=False, verbose_name='American Indian or Alaska Native'),
        ),
        migrations.AddField(
            model_name='wioa',
            name='asian',
            field=models.BooleanField(default=False, verbose_name='Asian'),
        ),
        migrations.AddField(
            model_name='wioa',
            name='black',
            field=models.BooleanField(default=False, verbose_name='Black or African American'),
        ),
        migrations.AddField(
            model_name='wioa',
            name='hispanic_latino',
            field=models.BooleanField(default=False, verbose_name='Hispanic/Latino'),
        ),
        migrations.AddField(
            model_name='wioa',
            name='pacific_islander',
            field=models.BooleanField(default=False, verbose_name='Native Hawaiian or Pacific Islander'),
        ),
        migrations.AddField(
            model_name='wioa',
            name='white',
            field=models.BooleanField(default=False, verbose_name='White'),
        ),
    ]
