# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20160925_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='native_language',
        ),
        migrations.AddField(
            model_name='wioa',
            name='country',
            field=models.CharField(blank=True, max_length=20, verbose_name='Country of Highest Education'),
        ),
        migrations.AddField(
            model_name='wioa',
            name='native_language',
            field=models.CharField(blank=True, max_length=20, verbose_name='Native Language'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ec_email',
            field=models.EmailField(blank=True, max_length=40, verbose_name='Their Email Address'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ec_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Their Phone Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ec_relation',
            field=models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Spouse'), ('B', 'Sibling'), ('F', 'Friend'), ('G', 'Legal Guardian'), ('O', 'Other')], default='O', max_length=1, verbose_name='Their Relationship to You'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=60, verbose_name='Emergency Contact Full Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VT', 'Vermont'), ('WV', 'West Virginia'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='LA', max_length=2),
        ),
        migrations.AlterField(
            model_name='staff',
            name='street_address_1',
            field=models.CharField(max_length=60, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='ec_email',
            field=models.EmailField(blank=True, max_length=40, verbose_name='Their Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ec_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Their Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ec_relation',
            field=models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Spouse'), ('B', 'Sibling'), ('F', 'Friend'), ('G', 'Legal Guardian'), ('O', 'Other')], default='O', max_length=1, verbose_name='Their Relationship to You'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=60, verbose_name='Emergency Contact Full Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='prior_registration',
            field=models.BooleanField(default=False, help_text='Have you registered with this program in the past?', verbose_name='Returning Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'District of Columbia'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MA', 'Massachusetts'), ('MD', 'Maryland'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VA', 'Virginia'), ('VT', 'Vermont'), ('WV', 'West Virginia'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='LA', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='street_address_1',
            field=models.CharField(max_length=60, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='occupation',
            field=models.CharField(blank=True, max_length=25, verbose_name='Occupation'),
        ),
    ]
