# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20160928_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wioa',
            name='disability_status',
        ),
        migrations.RemoveField(
            model_name='wioa',
            name='free_lunch_youth',
        ),
        migrations.RemoveField(
            model_name='wioa',
            name='homeless',
        ),
        migrations.RemoveField(
            model_name='wioa',
            name='low_income',
        ),
        migrations.RemoveField(
            model_name='wioa',
            name='low_literacy',
        ),
        migrations.RemoveField(
            model_name='wioa',
            name='public_assistance',
        ),
        migrations.AlterField(
            model_name='wioa',
            name='aged_out_foster_care',
            field=models.BooleanField(default=False, verbose_name='Have you aged out of foster care?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='country',
            field=models.CharField(blank=True, max_length=20, verbose_name='Country of Origin - if not US'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='cult_barriers_hind_emp',
            field=models.BooleanField(default=False, verbose_name='Are there cultural barriers hindering your employment?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='current_employment_status',
            field=models.CharField(choices=[('1', 'Employed'), ('2', 'Unemployed'), ('3', 'Unemployed - Not looking for work'), ('4', 'Not in labor force'), ('5', 'Employed, but recieved notice of termination or Military seperation is pending'), ('6', 'Not in labor force and/or not looking for work')], default='2', max_length=2, verbose_name='What is your current employment status'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='dislocated_worker',
            field=models.BooleanField(default=False, verbose_name='Are you a dislocated worker?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='displaced_homemaker',
            field=models.BooleanField(default=False, verbose_name='Are you a displaced homemaker?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='exhaust_tanf',
            field=models.BooleanField(default=False, verbose_name='Are you recieving TANF assistance that ends within 2 years?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='in_foster_care',
            field=models.BooleanField(default=False, verbose_name='Are you currently in foster care?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='job_corps',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Unknown')], max_length=1, verbose_name='Are you in Job Corps?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='native_language',
            field=models.CharField(blank=True, max_length=20, verbose_name='Native Language - if not English'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='recieves_public_assistance',
            field=models.BooleanField(default=False, verbose_name='Do you recieve public assistance?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='rural_area',
            field=models.BooleanField(default=False, verbose_name='Do you live in a rural area?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='single_parent',
            field=models.BooleanField(default=False, verbose_name='Are you a single parent?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='youth_build',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Unknown')], max_length=1, verbose_name='Are you in a Youth Build program?'),
        ),
    ]
