# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20160929_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wioa',
            options={'verbose_name_plural': 'WIOA records'},
        ),
        migrations.AddField(
            model_name='student',
            name='ace',
            field=models.BooleanField(default=False, verbose_name='ACE Program'),
        ),
        migrations.AddField(
            model_name='student',
            name='ccr',
            field=models.BooleanField(default=False, verbose_name='College and Career Readiness'),
        ),
        migrations.AddField(
            model_name='student',
            name='e_learn',
            field=models.BooleanField(default=False, verbose_name='Online Classes'),
        ),
        migrations.AddField(
            model_name='student',
            name='esl',
            field=models.BooleanField(default=False, verbose_name='English Language Learning'),
        ),
        migrations.AddField(
            model_name='student',
            name='success',
            field=models.BooleanField(default=False, verbose_name='Success Classes'),
        ),
    ]
