# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 17:20
from __future__ import unicode_literals

from django.db import migrations


def program_choices(apps, schema_editor):
	Student = apps.get_model('people', 'Student')
	for student in Student.objects.all():
		if student.program == 'C':
			student.ccr = True
		if student.program == 'E':
			student.esl = True
		if student.program == 'A':
			student.ace = True
		if student.program == 'D':
			student.e_learn = True
		if student.program == 'S':
			student.success = True
		student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20161019_1403'),
    ]

    operations = [
    	migrations.RunPython(program_choices)
    ]
