# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20161019_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ace',
            new_name='ace_app',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ccr',
            new_name='ccr_app',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='e_learn',
            new_name='e_learn_app',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='esl',
            new_name='esl_app',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='success',
            new_name='success_app',
        ),
    ]
