# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20161019_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='wioa',
            name='SID',
            field=models.CharField(blank=True, max_length=11, verbose_name='SSN'),
        ),
    ]
