# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_wioa_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='other_ID_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='What kind of ID is this?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_ID',
            field=models.CharField(blank=True, max_length=20, verbose_name='State ID, Passport #, Visa info, etc.'),
        ),
    ]
