# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_auto_20161213_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
