# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_auto_20170105_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ged_hiset', models.CharField(choices=[('1', 'Yes, high school diploma'), ('2', 'Yes, high school equivalency'), ('3', 'No')], max_length=1, verbose_name='Do you have a High School equivalency?')),
                ('current_adult_ed', models.BooleanField(default=True)),
                ('adult_ed_location', models.CharField(blank=True, max_length=50)),
                ('bpcc', models.BooleanField(default=False)),
                ('brcc', models.BooleanField(default=False)),
                ('ctcc', models.BooleanField(default=False)),
                ('dcc', models.BooleanField(default=False)),
                ('ldcc', models.BooleanField(default=False)),
                ('ftcc', models.BooleanField(default=False)),
                ('ntcc', models.BooleanField(default=False)),
                ('ncc', models.BooleanField(default=False)),
                ('nltc', models.BooleanField(default=False)),
                ('rpcc', models.BooleanField(default=False)),
                ('scl', models.BooleanField(default=False)),
                ('slcc', models.BooleanField(default=False)),
                ('sowela', models.BooleanField(default=False)),
                ('lola', models.CharField(blank=True, max_length=15)),
                ('other_college', models.BooleanField(default=False)),
                ('other_college_location', models.CharField(blank=True, max_length=30)),
                ('other_college_name', models.CharField(blank=True, max_length=50)),
                ('prev_balance', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('C', "I don't know")], max_length=1)),
                ('financial_aid', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('C', "I don't know")], max_length=1)),
                ('aid_status', models.CharField(choices=[('D', 'Default'), ('R', 'Repayment'), ('P', 'Paid in full'), ('U', "I don't know"), ('O', 'Other')], max_length=1)),
                ('nslds_notes', models.CharField(blank=True, max_length=200)),
                ('fafsa1617', models.BooleanField(default=False)),
                ('fafsa1718', models.BooleanField(default=False)),
                ('fafsa1819', models.BooleanField(default=False)),
                ('delgado_classes', models.CharField(blank=True, max_length=400)),
                ('employment_status', models.CharField(choices=[('F', 'Yes, I’m employed full-time (more than 30 hours per week).'), ('P', 'Yes, I’m employed part-time (less than 30 hours per week).'), ('L', 'No, but I’m looking for work.'), ('N', 'No, and I’m not looking for work right now.')], max_length=1)),
                ('work_schedule', models.CharField(blank=True, max_length=400)),
                ('carrer_goals', models.CharField(blank=True, max_length=2000)),
                ('notes', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'verbose_name_plural': 'College Interest Records',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='wru',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
