# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0022_auto_20170209_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeinterest',
            old_name='carrer_goals',
            new_name='career_goals',
        ),
        migrations.AddField(
            model_name='collegeinterest',
            name='cpr',
            field=models.BooleanField(default=False, verbose_name='CPR'),
        ),
        migrations.AddField(
            model_name='collegeinterest',
            name='first_aid',
            field=models.BooleanField(default=False, verbose_name='First Aid'),
        ),
        migrations.AddField(
            model_name='collegeinterest',
            name='ic3',
            field=models.BooleanField(default=False, verbose_name='Internet and Computing Core (IC3) Certification'),
        ),
        migrations.AddField(
            model_name='collegeinterest',
            name='nccer',
            field=models.BooleanField(default=False, verbose_name='NCCER Core Certification'),
        ),
        migrations.AddField(
            model_name='collegeinterest',
            name='serv_safe',
            field=models.BooleanField(default=False, verbose_name="ServSafe Manager's Level Certification"),
        ),
        migrations.AddField(
            model_name='collegeinterest',
            name='workforce_training',
            field=models.BooleanField(default=False, verbose_name='Have you ever take any workforce training classes?'),
        ),
        migrations.AddField(
            model_name='collegeinterest',
            name='workforce_training_desc',
            field=models.CharField(blank=True, max_length=50, verbose_name='What kind of workforce training classes?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='adult_ed_location',
            field=models.CharField(blank=True, max_length=50, verbose_name='Where?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='aid_status',
            field=models.CharField(choices=[('D', 'Default'), ('R', 'Repayment'), ('P', 'Paid in full'), ('U', "I don't know"), ('O', 'Other')], max_length=1, verbose_name='If you have used financial aid before, what is your current financial aid status?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='bpcc',
            field=models.BooleanField(default=False, verbose_name='Bossier Parish Community College (BPCC)'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='brcc',
            field=models.BooleanField(default=False, verbose_name='Baton Rouge Community College (BRCC)'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='ctcc',
            field=models.BooleanField(default=False, verbose_name='Central Louisiana Technical Community College (CTCC)'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='current_adult_ed',
            field=models.BooleanField(default=True, verbose_name='Check this box if you are currently attending adult education classes'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='dcc',
            field=models.BooleanField(default=False, verbose_name='Delgado Community College'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='delgado_classes',
            field=models.CharField(blank=True, max_length=400, verbose_name="If you've taken college classes at Delgado, please list the classes you took and when, to the best of your knowledge."),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='employment_status',
            field=models.CharField(choices=[('F', 'Yes, I’m employed full-time (more than 30 hours per week).'), ('P', 'Yes, I’m employed part-time (less than 30 hours per week).'), ('L', 'No, but I’m looking for work.'), ('N', 'No, and I’m not looking for work right now.')], max_length=1, verbose_name='Are you currently employed?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='fafsa1617',
            field=models.BooleanField(default=False, verbose_name='2016-2017'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='fafsa1718',
            field=models.BooleanField(default=False, verbose_name='2017-2018'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='fafsa1819',
            field=models.BooleanField(default=False, verbose_name='2018-2019'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='financial_aid',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('C', "I don't know")], max_length=1, verbose_name='Have you ever used financial aid (student loans or grants) before?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='ftcc',
            field=models.BooleanField(default=False, verbose_name='Fletcher Technical Community College'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='ged_hiset',
            field=models.CharField(choices=[('1', 'Yes, high school diploma'), ('2', 'Yes, high school equivalency'), ('3', 'No')], max_length=1, verbose_name='Do you have a your high school diploma or high school equivalency (GED/HiSET)?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='ldcc',
            field=models.BooleanField(default=False, verbose_name='Louisiana Delta Community College'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='lola',
            field=models.CharField(blank=True, max_length=15, verbose_name='Do you know your LOLA number?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='ncc',
            field=models.BooleanField(default=False, verbose_name='Nunez Community College'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='nltc',
            field=models.BooleanField(default=False, verbose_name='Northwest Louisiana Technical College'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='nslds_notes',
            field=models.CharField(blank=True, max_length=200, verbose_name='NLDS notes from ACE Staff:'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='ntcc',
            field=models.BooleanField(default=False, verbose_name='Northshore Technical Community College'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='other_college',
            field=models.BooleanField(default=False, verbose_name='Have you ever attended college before (anywhere)?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='other_college_location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Where was that?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='other_college_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Did you enroll under a different name than the one you gave us?'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='prev_balance',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('C', "I don't know")], max_length=1, verbose_name="If you've attended college before, do you owe a balance to that college?"),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='rpcc',
            field=models.BooleanField(default=False, verbose_name='River Parishes Community College (RPCC)'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='scl',
            field=models.BooleanField(default=False, verbose_name='South Central Louisiana Technical College (SCL)'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='slcc',
            field=models.BooleanField(default=False, verbose_name='South Louisiana Community College'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='sowela',
            field=models.BooleanField(default=False, verbose_name='Southwest Louisiana Technical Community College (SOWELA)'),
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=400, verbose_name='What is your usual work schedule like?'),
        ),
    ]
