# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_auto_20170216_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeinterest',
            name='career_goals',
            field=models.CharField(blank=True, max_length=2000, verbose_name='What kind of career would you like to have when you finish school?'),
        ),
    ]
