# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0024_auto_20170216_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeinterest',
            name='student',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='college_interest', to='people.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collegeinterest',
            name='ged_hiset',
            field=models.CharField(choices=[('1', 'Yes, high school diploma'), ('2', 'Yes, high school equivalency'), ('3', 'No')], max_length=1, verbose_name='Do you have your high school diploma or high school equivalency (GED/HiSET)?'),
        ),
    ]
