# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_auto_20170216_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name_plural': 'staff'},
        ),
    ]
