# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_auto_20170330_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accuplacer_app',
            field=models.BooleanField(default=False, verbose_name='Accuplacer'),
        ),
        migrations.AddField(
            model_name='student',
            name='eng_boot_app',
            field=models.BooleanField(default=False, verbose_name='Eng. Boot'),
        ),
        migrations.AddField(
            model_name='student',
            name='math_boot_app',
            field=models.BooleanField(default=False, verbose_name='Math Boot'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ace_app',
            field=models.BooleanField(default=False, verbose_name='ACE'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ccr_app',
            field=models.BooleanField(default=False, verbose_name='CCR'),
        ),
        migrations.AlterField(
            model_name='student',
            name='e_learn_app',
            field=models.BooleanField(default=False, verbose_name='ELearn'),
        ),
        migrations.AlterField(
            model_name='student',
            name='esl_app',
            field=models.BooleanField(default=False, verbose_name='ESL'),
        ),
        migrations.AlterField(
            model_name='student',
            name='success_app',
            field=models.BooleanField(default=False, verbose_name='Success'),
        ),
    ]
