# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20170405_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='ec_relation',
            field=models.CharField(choices=[('D', 'Father'), ('M', 'Mother'), ('S', 'Spouse'), ('B', 'Sibling'), ('F', 'Friend'), ('G', 'Legal Guardian'), ('O', 'Other')], default='O', max_length=1, verbose_name='Their Relationship to You'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ec_relation',
            field=models.CharField(choices=[('D', 'Father'), ('M', 'Mother'), ('S', 'Spouse'), ('B', 'Sibling'), ('F', 'Friend'), ('G', 'Legal Guardian'), ('O', 'Other')], default='O', max_length=1, verbose_name='Their Relationship to You'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='SID',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='SSN'),
        ),
    ]
