# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20170503_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='teacher',
            field=models.BooleanField(default=True),
        ),
    ]
