# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0030_auto_20170615_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
