# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0031_staff_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='g_suite_email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
