# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0035_auto_20180102_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name_plural': 'staff'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='school_status',
            field=models.CharField(blank=True, choices=[('1', 'In-School, H.S. or less'), ('2', 'In-School, Alternative School'), ('3', 'In-School, Post H.S.'), ('4', 'Not attending school or H.S. dropout'), ('5', 'Not attending school; H.S. graduate'), ('6', 'Not attending school; within age of compulsory school attendance')], default='4', max_length=1),
        ),
    ]
