# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0037_student_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='full_time',
            field=models.BooleanField(default=False),
        ),
    ]
