# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0038_staff_full_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
