# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-10 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0039_student_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dupl_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
