# Generated by Django 2.0.7 on 2018-07-12 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0040_student_dupl_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeinterest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='college_interest_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='WRU_ID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
