# Generated by Django 2.0.7 on 2018-10-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0041_auto_20180712_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wioa',
            name='job_corps',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Unknown')], default=2, max_length=1, verbose_name='Are you in Job Corps?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='youth_build',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No'), ('3', 'Unknown')], default=2, max_length=1, verbose_name='Are you in a Youth Build program?'),
        ),
    ]
