# Generated by Django 2.0.7 on 2019-02-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0043_student_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='orientation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='paperwork',
            field=models.BooleanField(default=False),
        ),
    ]
