# Generated by Django 2.0.7 on 2019-03-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0044_auto_20190215_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='paperwork',
        ),
    ]
