# Generated by Django 2.0.7 on 2019-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0045_auto_20190301_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='folder',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('I', 'Incomplete'), ('C', 'Complete')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='orientation',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('I', 'Incomplete'), ('C', 'Complete')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='paperwork',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('I', 'Incomplete'), ('C', 'Complete')], default='P', max_length=1),
        ),
    ]
