# Generated by Django 2.0.7 on 2019-09-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0047_auto_20190509_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Alternate Email Address'),
        ),
        migrations.AddField(
            model_name='student',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='Alternate Email Address'),
        ),
    ]
