# Generated by Django 2.0.7 on 2019-09-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0048_auto_20190903_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='partner',
            field=models.BooleanField(default=False),
        ),
    ]
