# Generated by Django 2.2.5 on 2019-12-11 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0049_staff_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicated_by', to='people.Student'),
        ),
    ]
