# Generated by Django 2.2.5 on 2019-12-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0050_student_duplicate_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paperwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferpa', models.BooleanField(default=False, verbose_name='FERPA')),
                ('test_and_comp', models.BooleanField(default=False, verbose_name='Test and Computer Usage Policy')),
                ('contract', models.BooleanField(default=False, verbose_name='Student Contract')),
                ('disclosure', models.BooleanField(default=False, verbose_name='Self-Disclosure Form')),
                ('lsi', models.BooleanField(default=False, verbose_name='Learning Style Inventory')),
                ('writing', models.BooleanField(default=False, verbose_name='Writing Sample')),
                ('pic_id', models.BooleanField(default=False, verbose_name='Picture ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_paperwork', to='people.Student')),
            ],
            options={
                'verbose_name_plural': 'paperwork',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
    ]
