# Generated by Django 2.2.10 on 2020-06-05 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0052_auto_20200409_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 6, 5), null=True),
        ),
    ]
