# Generated by Django 3.0.8 on 2020-07-20 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0053_auto_20200605_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 7, 20), null=True),
        ),
    ]
