# Generated by Django 3.0.8 on 2020-08-13 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0054_auto_20200720_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 8, 13), null=True),
        ),
    ]
