# Generated by Django 3.0.8 on 2020-10-05 22:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0056_auto_20200828_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 5), null=True),
        ),
        migrations.CreateModel(
            name='PoP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('last_service_date', models.DateField(verbose_name='Date of last service')),
                ('active', models.BooleanField(default=True)),
                ('made_gain', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop', to='people.Student')),
            ],
            options={
                'verbose_name_plural': 'Periods of Participation',
                'ordering': ['-start_date', 'student'],
                'get_latest_by': 'last_service_date',
                'unique_together': {('student', 'start_date')},
            },
        ),
    ]
