# Generated by Django 3.0.8 on 2020-10-12 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0057_auto_20201005_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 12), null=True),
        ),
    ]
