# Generated by Django 3.0.8 on 2020-10-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0058_auto_20201012_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='efl',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pop',
            name='pretest_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pop',
            name='pretest_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pop',
            name='tracking_subject',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
