# Generated by Django 3.0.8 on 2020-10-13 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0059_auto_20201012_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pop',
            name='efl',
        ),
        migrations.RemoveField(
            model_name='pop',
            name='tracking_subject',
        ),
        migrations.AlterField(
            model_name='student',
            name='intake_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 13), null=True),
        ),
    ]
