# Generated by Django 3.0.8 on 2020-10-13 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0060_auto_20201013_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='intake_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
