# Generated by Django 3.0.8 on 2020-10-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0061_auto_20201013_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pop',
            options={'get_latest_by': 'last_service_date', 'ordering': ['-start_date', 'student'], 'verbose_name': 'Period of Participation', 'verbose_name_plural': 'Periods of Participation'},
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='native_language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('spanish', 'Spanish'), ('vietnamese', 'Vietnamese'), ('arabic', 'Arabic'), ('chinese', 'Chinese'), ('french', 'French'), ('korean', 'Korean'), ('japanese', 'Japanese'), ('creole', 'Creole'), ('portugese', 'Portugese'), ('turkish', 'Turkish'), ('russian', 'Russian'), ('other', 'Other')], max_length=20, verbose_name='Native Language'),
        ),
    ]
