# Generated by Django 3.0.8 on 2021-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0062_auto_20201019_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='intake_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='intake_quiz',
            field=models.BooleanField(default=False),
        ),
    ]
