# Generated by Django 3.0.8 on 2021-04-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0063_auto_20210205_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Preferred Name or Nickname'),
        ),
        migrations.AddField(
            model_name='staff',
            name='pronoun',
            field=models.CharField(blank=True, choices=[('He/Him/His', 'He/Him/His'), ('She/Her/Hers', 'She/Her/Hers'), ('They/Them/Theirs', 'They/Them/Theirs'), ('Ze/Hir/Hirs', 'Ze/Hir/Hirs'), ('I do not use a pronoun', 'I do not use a pronoun'), ('Other, please ask', 'Other, please ask'), ('I use all gender pronouns', 'I use all gender pronouns')], max_length=25, verbose_name='Pronouns'),
        ),
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, choices=[('Mx.', 'Mx.'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], max_length=5, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='student',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Preferred Name or Nickname'),
        ),
        migrations.AddField(
            model_name='student',
            name='pronoun',
            field=models.CharField(blank=True, choices=[('He/Him/His', 'He/Him/His'), ('She/Her/Hers', 'She/Her/Hers'), ('They/Them/Theirs', 'They/Them/Theirs'), ('Ze/Hir/Hirs', 'Ze/Hir/Hirs'), ('I do not use a pronoun', 'I do not use a pronoun'), ('Other, please ask', 'Other, please ask'), ('I use all gender pronouns', 'I use all gender pronouns')], max_length=25, verbose_name='Pronouns'),
        ),
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(blank=True, choices=[('Mx.', 'Mx.'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.')], max_length=5, verbose_name='Title'),
        ),
    ]
