# Generated by Django 3.0.8 on 2021-05-07 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0065_auto_20210420_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=80, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('contact_preference', models.CharField(choices=[('Call', 'Call'), ('Text', 'Text'), ('Email', 'Email')], max_length=5, verbose_name='How do you prefer to be contacted?')),
                ('primary_language', models.CharField(blank=True, choices=[('english', 'English'), ('spanish', 'Spanish'), ('vietnamese', 'Vietnamese'), ('arabic', 'Arabic'), ('chinese', 'Chinese'), ('french', 'French'), ('korean', 'Korean'), ('japanese', 'Japanese'), ('creole', 'Creole'), ('portugese', 'Portugese'), ('turkish', 'Turkish'), ('russian', 'Russian'), ('other', 'Other')], max_length=20, verbose_name='Primary Language')),
                ('active', models.BooleanField(default=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='people.Staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prospects', to='people.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ProspectNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField()),
                ('contact_method', models.CharField(choices=[('Call', 'Call'), ('Text', 'Text'), ('Email', 'Email')], max_length=5)),
                ('successful', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='people.Prospect')),
            ],
        ),
    ]
