# Generated by Django 3.0.8 on 2021-05-07 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0066_prospect_prospectnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
