# Generated by Django 3.0.8 on 2021-05-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0067_prospect_registration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='staff',
            name='prospect_advisor',
            field=models.BooleanField(default=False),
        ),
    ]
