# Generated by Django 3.0.8 on 2021-06-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0068_auto_20210519_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospectnote',
            options={'ordering': ['contact_date', 'prospect']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='AEP_ID',
        ),
    ]
