# Generated by Django 3.0.8 on 2021-08-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0069_auto_20210616_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='duplicate',
            field=models.BooleanField(default=False, verbose_name='Probable Duplicate'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='for_credit',
            field=models.BooleanField(default=False, verbose_name='For-credit Student'),
        ),
    ]
