# Generated by Django 3.0.14 on 2021-08-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0070_auto_20210809_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospectnote',
            name='contact_method',
            field=models.CharField(choices=[('Call', 'Call'), ('Text', 'Text'), ('Email', 'Email'), ('In Person', 'In Person')], max_length=10),
        ),
    ]
