# Generated by Django 3.0.14 on 2021-08-18 00:16

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0071_auto_20210810_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='slug',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.CharField(default=people.models.make_staff_slug, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.CharField(default=people.models.make_student_slug, max_length=5, unique=True),
        ),
    ]
