# Generated by Django 3.0.14 on 2021-11-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0073_auto_20210818_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='esl_app',
            new_name='ell_app',
        ),
    ]
