# Generated by Django 3.0.14 on 2021-11-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0074_auto_20211109_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectnote',
            name='returning_student',
            field=models.BooleanField(default=False, verbose_name='Returning Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ell_app',
            field=models.BooleanField(default=False, verbose_name='ELL'),
        ),
    ]
