# Generated by Django 3.0.14 on 2021-12-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0076_prospect_returning_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certifications_app',
            field=models.BooleanField(default=False, verbose_name='Certifications'),
        ),
        migrations.AddField(
            model_name='student',
            name='ell_online_app',
            field=models.BooleanField(default=False, verbose_name='ELL Online'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ccr_app',
            field=models.BooleanField(default=False, verbose_name='HiSET In-Person'),
        ),
        migrations.AlterField(
            model_name='student',
            name='e_learn_app',
            field=models.BooleanField(default=False, verbose_name='HiSET Online'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ell_app',
            field=models.BooleanField(default=False, verbose_name='ELL In-Person'),
        ),
    ]
