# Generated by Django 3.0.14 on 2022-02-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0077_auto_20211214_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='advisor_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='contact_time',
            field=models.CharField(blank=True, choices=[('M', '8am - 12pm'), ('A', '12pm - 4pm'), ('E', '4pm - 8pm')], max_length=1, verbose_name='What time do you prefer to be contacted?'),
        ),
    ]
