# Generated by Django 4.0.4 on 2022-08-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0080_alter_staff_city_alter_student_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wioa',
            name='state_id_checked',
            field=models.BooleanField(default=False),
        ),
    ]
