# Generated by Django 4.0.4 on 2022-08-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0083_alter_wioa_current_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wioa',
            name='current_employment_status',
            field=models.CharField(choices=[('1', 'Employed - Full Time'), ('9', 'Employed - Part Time'), ('2', 'Unemployed - Looking For Work'), ('3', 'Unemployed - Not Looking for work'), ('4', 'Not in labor force/ Not available for work'), ('5', 'Employed, but recieved notice of termination or Military seperation is pending'), ('6', 'Not in labor force and/or not looking for work'), ('7', 'Retired')], default='2', max_length=2, verbose_name='What is your current employment status'),
        ),
    ]
