# Generated by Django 4.0.4 on 2022-09-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0085_alter_staff_city_alter_student_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, choices=[('Mx.', 'Mx.'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Dr.', 'Dr.')], max_length=5, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_ID',
            field=models.CharField(blank=True, max_length=20, verbose_name='State ID, Passport #, Visa info, etc. (Optional)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='other_ID_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='What kind of ID is this? (Optional)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.CharField(blank=True, choices=[('Mx.', 'Mx.'), ('Miss', 'Miss'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Dr.', 'Dr.')], max_length=5, verbose_name='Title'),
        ),
    ]
