# Generated by Django 4.0.4 on 2022-10-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0086_alter_staff_title_alter_student_other_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wioa',
            name='TANF_2',
            field=models.BooleanField(default=False, verbose_name='Have you received TANF for more than two years in total?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='current_employment_status',
            field=models.CharField(choices=[('1', 'Employed - Full Time'), ('9', 'Employed - Part Time'), ('5', 'Employed, but received notice of termination or Military separation is pending'), ('2', 'Unemployed - Looking For Work'), ('4', 'Not in labor force / Not looking for work'), ('7', 'Retired')], default='2', max_length=2, verbose_name='What is your current employment status'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='exhaust_tanf',
            field=models.BooleanField(default=False, verbose_name='Are you receiving TANF assistance that ends within 2 years?'),
        ),
        migrations.AlterField(
            model_name='wioa',
            name='recieves_public_assistance',
            field=models.BooleanField(default=False, verbose_name='Do you receive public assistance?'),
        ),
    ]
