# Generated by Django 4.0.4 on 2022-10-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0087_alter_wioa_tanf_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperwork',
            name='lsi',
        ),
        migrations.RemoveField(
            model_name='paperwork',
            name='test_and_comp',
        ),
        migrations.AddField(
            model_name='paperwork',
            name='g_sig_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='guardian_signature',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sd_attention',
            field=models.BooleanField(default=False, verbose_name='Attention Deficit Disorder/Attention Deficit Hyperactivity Disorder'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sd_language',
            field=models.BooleanField(default=False, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sd_math',
            field=models.BooleanField(default=False, verbose_name='Math'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sd_other',
            field=models.CharField(blank=True, max_length=140, verbose_name='Other (explain)'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sd_reading',
            field=models.BooleanField(default=False, verbose_name='Reading'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sh_504',
            field=models.BooleanField(default=False, verbose_name='504 Accommodations'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sh_medication',
            field=models.BooleanField(default=False, verbose_name='Medication for A.D.D. or A.D.H.D'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sh_other',
            field=models.CharField(blank=True, max_length=140, verbose_name='Other (explain)'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sh_request',
            field=models.TextField(blank=True, verbose_name='I feel I need help in the following area(s):'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sh_resource_se',
            field=models.BooleanField(default=False, verbose_name='Resource Special Education Classroom'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sh_self_se',
            field=models.BooleanField(default=False, verbose_name='Self-contained Special Education Classroom'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sh_title1_math',
            field=models.BooleanField(default=False, verbose_name='Title 1 Math'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sh_title1_read',
            field=models.BooleanField(default=False, verbose_name='Title 1 Reading'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='sig_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='signature',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='technology',
            field=models.BooleanField(default=False, verbose_name='Teechnology Usage Agreement'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='testing',
            field=models.BooleanField(default=False, verbose_name='Testing Agreement'),
        ),
        migrations.AddField(
            model_name='paperwork',
            name='writing_sample',
            field=models.TextField(blank=True, verbose_name='Student Writing Sample'),
        ),
    ]
