# Generated by Django 4.0.4 on 2022-11-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0088_remove_paperwork_lsi_remove_paperwork_test_and_comp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperwork',
            name='pic_id_file',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paperwork',
            name='g_sig_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
