# Generated by Django 4.1.6 on 2023-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0091_student_mw_student_sat_student_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='afternoon',
            field=models.BooleanField(default=False, verbose_name='Afternoon (1:00pm - 4:00pm)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='evening',
            field=models.BooleanField(default=False, verbose_name='Evening (5:30pm - 8:30pm)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='morning',
            field=models.BooleanField(default=False, verbose_name='Morning (8:30am - 1:00pm)'),
        ),
    ]
