# Generated by Django 4.1.6 on 2023-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0041_cancellation_send_notification'),
        ('people', '0092_alter_student_afternoon_alter_student_evening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='site_preference',
            field=models.ManyToManyField(blank=True, to='sections.site'),
        ),
    ]
