# Generated by Django 4.2.10 on 2024-08-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0094_alter_staff_city_alter_student_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex'),
        ),
    ]
