# Generated by Django 4.2.10 on 2024-09-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0095_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='program',
            field=models.CharField(blank=True, choices=[('ccr', 'HiSET/GED'), ('ell', 'English Language Learning')], max_length=5, verbose_name='What classes are you interested in?'),
        ),
    ]
