# Generated by Django 5.1.2 on 2024-10-29 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_to', models.EmailField(blank=True, max_length=254)),
                ('allowed_absences', models.SmallIntegerField(default=4)),
            ],
            options={
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=160)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('sessions', models.ManyToManyField(to='semesters.semester')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, max_length=250)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='semesters.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('form_link', models.URLField(blank=True)),
                ('sessions', models.ManyToManyField(to='semesters.semester')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
