# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, max_length=250)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='semesters.Semester')),
            ],
        ),
    ]
