# Generated by Django 5.1.2 on 2025-06-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='first_class_report_to',
            field=models.EmailField(blank=True, help_text='Email address to receive first class drop warning reports', max_length=254),
        ),
        migrations.AlterField(
            model_name='semester',
            name='report_to',
            field=models.EmailField(blank=True, help_text='Email address to recieve attendance reminder reports', max_length=254),
        ),
    ]
