# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0003_auto_20161202_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='allowed_absences',
            field=models.SmallIntegerField(default=4),
        ),
    ]
