# Generated by Django 3.0.8 on 2020-08-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0005_auto_20190303_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
