# Generated by Django 3.0.8 on 2021-04-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0006_auto_20200828_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('form_link', models.URLField(blank=True)),
                ('sessions', models.ManyToManyField(to='semesters.Semester')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
