# Generated by Django 3.0.14 on 2021-09-28 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0007_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=160)),
                ('sessions', models.ManyToManyField(to='semesters.Semester')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
