# Generated by Django 3.0.14 on 2022-01-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
