# Generated by Django 4.1.6 on 2023-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semesters', '0009_message_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='report_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
