# Generated by Django 4.0.4 on 2022-12-09 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='return_date',
            new_name='returned_date',
        ),
    ]
