# Generated by Django 4.1.6 on 2023-02-10 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0090_alter_paperwork_technology'),
        ('inventory', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='return_req_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='people.staff'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='people.student'),
        ),
    ]
