# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.CharField(blank=True, choices=[('Morning', 'Morning (8am - 12am)'), ('Afternoon', 'Afternoon (12am - 4pm)'), ('Evening', 'Early Evening (4pm - 8pm)')], max_length=11, verbose_name='What is your typical availability?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='best_classes',
            field=models.TextField(verbose_name='What classes were you best at?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_preference',
            field=models.CharField(choices=[('Call', 'Call'), ('Text', 'Text'), ('Email', 'Email'), ('Social Media', 'Social Media'), ('Google Chat', 'Google Chat')], max_length=12, verbose_name='How do you prefer to be contacted?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='device',
            field=models.CharField(max_length=50, verbose_name='What device will you be using for online learning?(e.g Phone, Tablet, Computer, etc.)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='library',
            field=models.CharField(choices=[('Yes Close and Card', 'Yes, I live close and I have a card'), ('Yes Close', 'Yes, I live close'), ('No not Near', "No, I don't live near a library"), ('No Access Hours', "No, I don't have access to a library during the hours they are open."), ('Unsure', "I'm not sure if I live near a library.")], max_length=20, verbose_name='Do you have access to a local library?'),
        ),
    ]
