# Generated by Django 5.1.2 on 2025-01-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_serviceprovider_accommodations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acerecord',
            name='bls_cert',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='eng_062',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='math_092',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='math_098',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='math_exit',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='microsoft_cert',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='nccer_cert',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='read_072',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='reading_exit',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='servsafe_cert',
        ),
        migrations.RemoveField(
            model_name='acerecord',
            name='writing_exit',
        ),
        migrations.AddField(
            model_name='acerecord',
            name='five_for_six_agreement',
            field=models.BooleanField(default=False, verbose_name='5 for 6 Agreement Signed'),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='five_for_six_agreement_date',
            field=models.DateField(blank=True, null=True, verbose_name='5 for 6 Agreement Sign Date'),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='media_release_accept',
            field=models.BooleanField(default=False, verbose_name='Media Release Decision'),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='media_release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Media Release Sign Date'),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='signature',
            field=models.CharField(blank=True, max_length=140, verbose_name='Digital Signature'),
        ),
        migrations.AlterField(
            model_name='acerecord',
            name='media_release',
            field=models.BooleanField(default=False, verbose_name='Media Release Signed'),
        ),
    ]
