# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_auto_20170518_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='coaching_type',
            field=models.CharField(choices=[('elearn', 'eLearn'), ('ace', 'ACE'), ('open', 'Open Coaching')], default='open', help_text='Type of coaching (Choose One)', max_length=6),
        ),
        migrations.AlterField(
            model_name='acerecord',
            name='hsd',
            field=models.CharField(choices=[('HSE', 'HSE'), ('HSD', 'HSD'), ('Neither', 'Neither')], default='Neither', max_length=7),
        ),
        migrations.AlterField(
            model_name='acerecord',
            name='hsd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='meeting_type',
            field=models.CharField(choices=[('Academic Planning', 'Academic Planning'), ('Personal', 'Personal'), ('Coaching Check-in', 'Coaching Check-in'), ('Other', 'Other')], help_text='Type of coaching (Choose One)', max_length=6),
        ),
    ]
