# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_auto_20170524_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingnote',
            name='meeting_type',
            field=models.CharField(choices=[('Academic Planning', 'Academic Planning'), ('Personal', 'Personal'), ('Coaching Check-in', 'Coaching Check-in'), ('Other', 'Other')], help_text='Type of coaching (Choose One)', max_length=17),
        ),
    ]
