# Generated by Django 5.2.13 on 2026-05-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0003_remove_acerecord_bls_cert_remove_acerecord_eng_062_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnote',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
