# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0004_auto_20170524_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acerecord',
            name='ace_pathway',
            field=models.CharField(blank=True, choices=[('Healthcare', 'Healthcare'), ('Skilled Crafts', 'Skilled Crafts'), ('IT', 'IT'), ('Hospitality', 'Culinary Arts / Hospitality')], max_length=15),
        ),
        migrations.AlterField(
            model_name='acerecord',
            name='hsd',
            field=models.CharField(blank=True, choices=[('HSE', 'HSE'), ('HSD', 'HSD'), ('Neither', 'Neither')], default='Neither', max_length=7),
        ),
        migrations.AlterField(
            model_name='acerecord',
            name='program',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='acerecord',
            name='third_party_release',
            field=models.BooleanField(default=False),
        ),
    ]
