# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-09 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0005_auto_20170605_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='acerecord',
            name='ace_status',
            field=models.CharField(blank=True, choices=[('Deferred', 'Deferred'), ('Active', 'Active'), ('InActive', 'InActive'), ('Completed', 'Completed')], max_length=9),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='intake_semester',
            field=models.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Summer', 'Summer')], max_length=6),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='intake_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='status_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='student_no_show',
            field=models.BooleanField(default=False, help_text='Check this box if the student failed to attend the meeting'),
        ),
    ]
