# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0007_elearnrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingnote',
            options={'ordering': ['-meeting_date']},
        ),
    ]
