# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0008_auto_20170705_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
