# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0010_auto_20170820_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnote',
            name='ace_withdrawl',
            field=models.BooleanField(default=False, verbose_name='Concern: Coach Unable to Reach'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='cannot_reach',
            field=models.BooleanField(default=False, verbose_name='Concern: Coach Unable to Reach'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='class_absences',
            field=models.BooleanField(default=False, verbose_name='Concern: Class Absences'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='coach_cancel',
            field=models.BooleanField(default=False, help_text='Check this box if the coach cancelled the meeting'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='low_grades',
            field=models.BooleanField(default=False, verbose_name='Concern: Low Grades'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='meeting_absences',
            field=models.BooleanField(default=False, verbose_name='Concern: Meeting Absences'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='student_cancel',
            field=models.BooleanField(default=False, help_text='Check this box if the student cancelled the meeting'),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='student_reschedule',
            field=models.BooleanField(default=False, help_text='Check this box if the student requested to reschedule the meeting'),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='meeting_type',
            field=models.CharField(choices=[('College Options', 'Discuss College Options'), ('Next Steps', 'Plan Next Steps'), ('Schedule Classes', 'Schedule Next Classes'), ('Build Skills', 'Build Student Skills'), ('eLearn Check-in', 'eLearn Check-in'), ('ACE Coaching', 'ACE Student Coaching'), ('Return to ACE', 'Plan for Return to ACE')], help_text='Type of coaching (Choose One)', max_length=17),
        ),
    ]
