# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0011_auto_20170824_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingnote',
            name='ace_withdrawl',
            field=models.BooleanField(default=False, verbose_name='Withdawing from Ace'),
        ),
    ]
