# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0012_auto_20170920_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearnrecord',
            name='elearn_status',
            field=models.CharField(blank=True, choices=[('Applicant', 'Applicant'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Active', 'Active'), ('InActive', 'InActive')], default='Applicant', max_length=9),
        ),
    ]
