# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-02 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0013_auto_20171016_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearnrecord',
            name='elearn_status',
            field=models.CharField(blank=True, choices=[('Applicant', 'Applicant'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Active', 'Active'), ('InActive', 'InActive'), ('Alumni', 'Alumni')], default='Applicant', max_length=9),
        ),
    ]
