# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0014_auto_20180102_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['student__last_name', 'student__first_name']},
        ),
    ]
