# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0015_auto_20180117_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acerecord',
            name='ace_status',
            field=models.CharField(blank=True, choices=[('Applicant', 'Applicant'), ('Pending', 'Pending'), ('Deferred', 'Deferred'), ('Active', 'Active'), ('InActive', 'InActive'), ('Completed', 'Completed')], max_length=9),
        ),
    ]
