# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0016_auto_20180208_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearnrecord',
            name='elearn_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Applicant', 'Applicant'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Active', 'Active'), ('InActive', 'InActive'), ('Alumni', 'Alumni')], default='Applicant', max_length=9),
        ),
    ]
