# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-04 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0017_auto_20180308_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='acerecord',
            name='eng_062',
            field=models.BooleanField(default=False, verbose_name='Passed ENG 062'),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='math_092',
            field=models.BooleanField(default=False, verbose_name='Passed MATH 092'),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='math_098',
            field=models.BooleanField(default=False, verbose_name='Passed MATH 098'),
        ),
        migrations.AddField(
            model_name='acerecord',
            name='read_072',
            field=models.BooleanField(default=False, verbose_name='Passed Townsend'),
        ),
    ]
