# Generated by Django 2.0.7 on 2018-07-12 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0018_auto_20180404_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coachees', to='people.Staff'),
        ),
    ]
