# Generated by Django 2.0.7 on 2019-01-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0019_auto_20180712_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnote',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('hangouts', 'Google Hangouts'), ('messenger', 'Facebook Messenger')], max_length=10),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='meeting_topic',
            field=models.TextField(blank=True, choices=[('personal', 'Personal'), ('classwork', 'Classwork/Tutoring'), ('hiset', 'Official HiSET Registration/Prep'), ('practice test', 'Practice Testing'), ('course planning', 'Course Planning'), ('success skills', 'Success Skills'), ('retention', 'Retention'), ('next steps', 'Plan Next Steps'), ('discuss college options', 'Discuss College Options')]),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='multiple_days',
            field=models.BooleanField(default=False, verbose_name='Meeting took place over multiple days'),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='meeting_type',
            field=models.CharField(choices=[('eLearn', 'eLearn'), ('ACE', 'ACE'), ('Open Coaching', 'Open Coaching')], help_text='Type of coaching (Choose One)', max_length=17),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='next_steps',
            field=models.TextField(blank=True, choices=[('standard check-in', 'Standard check-in'), ('follow up', 'Follow-up with online resources'), ('contact teacher', 'Contact teacher'), ('refer to on campus resources', 'Refer to on-campus resources'), ('reccomend HISET', 'Recommend HISET')]),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
