# Generated by Django 2.0.7 on 2019-01-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0021_auto_20190104_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingnote',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text'), ('hangouts', 'Google Hangouts'), ('messenger', 'Facebook Messenger'), ('In person', 'In Person')], max_length=10),
        ),
    ]
