# Generated by Django 2.0.7 on 2019-09-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0022_auto_20190104_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearnrecord',
            name='elearn_status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Applicant', 'Applicant'), ('Pending', 'Pending'), ('On Hold', 'On Hold'), ('Active', 'Active'), ('InActive', 'InActive'), ('Alumni', 'Alumni'), ('Partner', 'Partner'), ('Partner Alumnus', 'Partner Alumnus'), ('Campus', 'Campus')], default='Applicant', max_length=15),
        ),
    ]
