# Generated by Django 2.2.10 on 2020-06-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0024_auto_20200409_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Inactive', 'Inactive'), ('ESL > CCR', 'ESL > CCR'), ('Completed HiSET', 'Completed HiSET')], default='Active', max_length=20),
        ),
    ]
