# Generated by Django 3.0.8 on 2020-10-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0025_coaching_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elearnrecord',
            name='g_suite_email',
            field=models.EmailField(blank=True, max_length=60),
        ),
    ]
