# Generated by Django 3.0.8 on 2021-04-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0026_auto_20201005_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnote',
            name='duration',
            field=models.TextField(blank=True, choices=[('15', '15 min'), ('30', '30 min'), ('45', '45 min'), ('60', '60 min')], max_length=3),
        ),
    ]
