# Generated by Django 3.0.14 on 2021-11-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0027_meetingnote_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaching',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Inactive', 'Inactive'), ('ELL > CCR', 'ELL > CCR'), ('Completed HiSET', 'Completed HiSET')], default='Active', max_length=20),
        ),
    ]
