# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clas_e',
            options={'verbose_name': 'CLAS-E', 'verbose_name_plural': 'CLAS-E scores'},
        ),
        migrations.AlterModelOptions(
            name='hiset_practice',
            options={'verbose_name': 'HiSET Practice', 'verbose_name_plural': 'HiSET Practice scores'},
        ),
        migrations.AlterModelOptions(
            name='tabe',
            options={'verbose_name': 'TABE', 'verbose_name_plural': 'TABE scores'},
        ),
        migrations.AlterModelOptions(
            name='testappointment',
            options={'verbose_name': 'Testing Appointment', 'verbose_name_plural': 'Testing Appointments'},
        ),
        migrations.AlterModelOptions(
            name='testevent',
            options={'verbose_name': 'Test Event', 'verbose_name_plural': 'Test Events'},
        ),
        migrations.AddField(
            model_name='testevent',
            name='full',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testappointment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='assessments.TestEvent'),
        ),
    ]
