# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20170112_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testhistory',
            name='current_pretest',
        ),
        migrations.RemoveField(
            model_name='testhistory',
            name='hours',
        ),
        migrations.AddField(
            model_name='testhistory',
            name='test_assignment',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
