# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_auto_20170123_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas_e',
            name='student_wru',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='clas_e_loc',
            name='student_wru',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='hiset_practice',
            name='student_wru',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='tabe',
            name='student_wru',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='tabe_loc',
            name='student_wru',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
