# Generated by Django 5.1.2 on 2024-12-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_testingaccommodations_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testingaccommodations',
            options={'verbose_name': 'Testing Accommodation', 'verbose_name_plural': 'Testing Accommodations'},
        ),
    ]
