# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_20170125_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='student_wru',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
