# Generated by Django 5.1.2 on 2025-03-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_testingaccommodations_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabe',
            name='form',
            field=models.CharField(choices=[('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], max_length=2),
        ),
    ]
