# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_testhistory_student_wru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clas_e',
            name='student_wru',
        ),
        migrations.RemoveField(
            model_name='clas_e_loc',
            name='student_wru',
        ),
        migrations.RemoveField(
            model_name='hiset_practice',
            name='student_wru',
        ),
        migrations.RemoveField(
            model_name='tabe',
            name='student_wru',
        ),
        migrations.RemoveField(
            model_name='tabe_loc',
            name='student_wru',
        ),
    ]
