# Generated by Django 5.1.2 on 2025-06-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_tabe_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas_e',
            name='form',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
    ]
