# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_auto_20170220_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevent',
            name='title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
