# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_testevent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testevent',
            name='test',
            field=models.CharField(choices=[('TABE', 'TABE Test'), ('TABE Locator', 'TABE Locator'), ('CLAS-E', 'CLAS-E Test'), ('CLAS-E Locator', 'CLAS-E Locator'), ('Orientation', 'Orientation'), ('HiSET Practice', 'HiSET Practice'), ('Exit Exam', 'Exit Exam')], max_length=20),
        ),
    ]
