# Generated by Django 5.1.2 on 2026-02-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_clas_e_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='active_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testhistory',
            name='testing_status',
            field=models.CharField(blank=True, choices=[('No Test Needed', 'No Test Needed'), ('Test Needed', 'Test Needed'), ('Something is wrong', 'Something is wrong')], default='', max_length=20),
        ),
    ]
