# Generated by Django 5.1.2 on 2026-02-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_testhistory_active_hours_testhistory_testing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistory',
            name='active_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
