# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_auto_20170309_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testevent',
            options={'ordering': ['-start'], 'verbose_name': 'Test Event', 'verbose_name_plural': 'Test Events'},
        ),
        migrations.AddField(
            model_name='testevent',
            name='room',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
