# Generated by Django 5.1.2 on 2026-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_testhistory_active_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas_e',
            name='listen_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
        migrations.AddField(
            model_name='clas_e',
            name='listen_nrs',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='clas_e',
            name='listen_ss',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
