# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_auto_20170503_1300'),
        ('assessments', '0009_auto_20170330_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas_e',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clas_e_loc',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabe',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabe_loc',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='testappointment',
            unique_together=set([('student', 'event')]),
        ),
    ]
