# Generated by Django 5.2.13 on 2026-05-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_clas_e_listen_level_clas_e_listen_nrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testappointment',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
