# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_auto_20170503_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('reported', models.BooleanField(default=False)),
                ('form', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('English', 'English')], max_length=7)),
                ('scale_score', models.PositiveSmallIntegerField()),
                ('grade_eq', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nrs', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gain_tests', to='assessments.TestHistory')),
            ],
            options={
                'verbose_name_plural': 'GAIN Tests',
                'verbose_name': 'GAIN',
            },
        ),
        migrations.AddField(
            model_name='hiset_practice',
            name='grade',
            field=models.CharField(choices=[('Not yet prepared', 'Not yet prepared'), ('Somewhat prepared', 'Somewhat prepared'), ('Prepared', 'Prepared'), ('Well Prepared', 'Well Prepared')], default='', max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiset_practice',
            name='score',
            field=models.PositiveSmallIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiset_practice',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('Reading', 'Reading'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Writing', 'Writing'), ('Essay', 'Essay')], default='', max_length=14),
            preserve_default=False,
        ),
    ]
