# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_auto_20170507_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gain',
            options={'verbose_name': 'GAIN', 'verbose_name_plural': 'GAIN Scores'},
        ),
    ]
