# Generated by Django 2.0.7 on 2018-07-12 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0018_auto_20180601_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clas_e',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clas_e_tests', to='assessments.TestHistory'),
        ),
        migrations.AlterField(
            model_name='clas_e_loc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clas_e_loc_tests', to='assessments.TestHistory'),
        ),
        migrations.AlterField(
            model_name='gain',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gain_tests', to='assessments.TestHistory'),
        ),
        migrations.AlterField(
            model_name='hiset_practice',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hpt_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hiset_practice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiset_practice_tests', to='assessments.TestHistory'),
        ),
        migrations.AlterField(
            model_name='tabe',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabe_tests', to='assessments.TestHistory'),
        ),
        migrations.AlterField(
            model_name='tabe_loc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabe_loc_tests', to='assessments.TestHistory'),
        ),
        migrations.AlterField(
            model_name='testevent',
            name='proctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tests', to='people.Staff'),
        ),
    ]
