# Generated by Django 2.0.7 on 2019-03-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_auto_20190104_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='testappointment',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testappointment',
            name='attendance_type',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('X', 'Pending')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='testappointment',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testappointment',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
