# Generated by Django 2.0.7 on 2019-05-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_auto_20190302_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiset_practice',
            name='test_version',
            field=models.CharField(blank=True, choices=[('FPT2', 'Free Practice Test 2 (2015)'), ('FPT3', 'Free Practice Test 3 (2015)'), ('PPT2', 'Paid Practice Test 2 (2015)'), ('PPT3', 'Paid Practice Test 3 (2015)'), ('PPT4', 'Paid Practice Test 4 (2015)'), ('PPT5', 'Paid Practice Test 5 (2015)'), ('OPT2', 'Official Practice Test 2 (2015)'), ('OPT3', 'Official Practice Test 3 (2015)'), ('FPT6A', 'Free Practice Test 6A (2016)'), ('PPT6A', 'Paid Practice Test 6A (2016)'), ('OPT6A', 'Official Practice Test 6A (2016)'), ('FPT7', 'Free Practice Test 7 (2017)'), ('OPT7', 'Official Practice Test 7 (2017)'), ('OPT8', 'Official Practice Test 8 (2018)')], max_length=5),
        ),
    ]
