# Generated by Django 2.0.7 on 2019-07-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0028_auto_20190626_2036'),
        ('assessments', '0022_auto_20190509_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevent',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='sections.Site'),
        ),
    ]
