# Generated by Django 2.0.7 on 2019-09-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_testevent_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='testappointment',
            name='att_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
