# Generated by Django 3.0.8 on 2020-10-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_auto_20200409_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testhistory',
            old_name='last_test',
            new_name='last_test_date',
        ),
        migrations.AddField(
            model_name='testhistory',
            name='efl',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testhistory',
            name='last_test_type',
            field=models.CharField(blank=True, default='No Test', max_length=20),
        ),
        migrations.AddField(
            model_name='testhistory',
            name='tracking_subject',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
