# Generated by Django 3.0.8 on 2021-01-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0028_auto_20201013_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabe',
            name='lang_level',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('D', 'D'), ('M', 'M'), ('E', 'E'), ('L', 'L')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tabe',
            name='math_level',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('D', 'D'), ('M', 'M'), ('E', 'E'), ('L', 'L')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tabe',
            name='read_level',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('D', 'D'), ('M', 'M'), ('E', 'E'), ('L', 'L')], max_length=1),
        ),
    ]
