# Generated by Django 3.0.14 on 2021-07-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0030_auto_20210427_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testappointment',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='testevent',
            name='test',
            field=models.CharField(choices=[('TABE', 'TABE Test'), ('TABE Locator', 'TABE Locator'), ('CLAS-E', 'CLAS-E Test'), ('CLAS-E Locator', 'CLAS-E Locator'), ('Orientation', 'Orientation'), ('Online Orientation', 'Online Orientation'), ('HiSET Practice', 'HiSET Practice'), ('Exit Exam', 'Exit Exam')], max_length=20),
        ),
    ]
