# Generated by Django 3.0.14 on 2021-12-07 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0031_auto_20210715_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiSET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Reading', 'Reading'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Writing', 'Writing'), ('Essay', 'Essay')], max_length=14)),
                ('proctor', models.CharField(choices=[('Staff', 'Proctored by Staff Member'), ('Self', 'Self-Administered')], default='Staff', max_length=20)),
                ('score', models.PositiveSmallIntegerField()),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ht_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hiset_tests', to='assessments.TestHistory')),
            ],
            options={
                'verbose_name': 'HiSET',
                'verbose_name_plural': 'HiSET scores',
            },
        ),
        migrations.CreateModel(
            name='Accuplacer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('reading', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('writing', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quantitative', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('functions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('eng_placement', models.CharField(blank=True, max_length=100, null=True)),
                ('math_placement', models.CharField(blank=True, max_length=100, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accuplacer_tests', to='assessments.TestHistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
