# Generated by Django 3.0.14 on 2021-12-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0032_accuplacer_hiset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiset',
            options={'verbose_name': 'Official HiSET', 'verbose_name_plural': 'Official HiSET scores'},
        ),
    ]
