# Generated by Django 3.0.14 on 2022-01-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0033_auto_20211214_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiset',
            name='proctor',
        ),
    ]
