# Generated by Django 3.0.14 on 2022-01-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0034_remove_hiset_proctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiset',
            name='reported_by',
        ),
    ]
