# Generated by Django 3.0.14 on 2022-01-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_remove_hiset_reported_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=160)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('events', models.ManyToManyField(to='assessments.TestEvent')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
