# Generated by Django 3.0.14 on 2022-01-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0036_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas_e',
            name='score_report_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clas_e_loc',
            name='score_report_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gain',
            name='score_report_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tabe',
            name='score_report_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tabe_loc',
            name='score_report_link',
            field=models.URLField(blank=True),
        ),
    ]
