# Generated by Django 4.0.4 on 2022-07-12 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0037_auto_20220118_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accuplacer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tests', to='assessments.testhistory'),
        ),
        migrations.AlterField(
            model_name='clas_e',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tests', to='assessments.testhistory'),
        ),
        migrations.AlterField(
            model_name='clas_e_loc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tests', to='assessments.testhistory'),
        ),
        migrations.AlterField(
            model_name='gain',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tests', to='assessments.testhistory'),
        ),
        migrations.AlterField(
            model_name='hiset',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tests', to='assessments.testhistory'),
        ),
        migrations.AlterField(
            model_name='hiset_practice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tests', to='assessments.testhistory'),
        ),
        migrations.AlterField(
            model_name='tabe',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tests', to='assessments.testhistory'),
        ),
        migrations.AlterField(
            model_name='tabe_loc',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_tests', to='assessments.testhistory'),
        ),
    ]
