# Generated by Django 4.0.4 on 2022-09-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0038_alter_accuplacer_student_alter_clas_e_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clas_e',
            unique_together={('student', 'test_date', 'form', 'read_level', 'read_nrs')},
        ),
        migrations.AlterUniqueTogether(
            name='tabe',
            unique_together={('student', 'test_date', 'form', 'read_level', 'math_level', 'lang_level', 'read_nrs', 'math_nrs', 'lang_nrs')},
        ),
    ]
