# Generated by Django 4.0.4 on 2022-09-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0039_alter_clas_e_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas_e',
            name='score_report_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clas_e_loc',
            name='score_report_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gain',
            name='score_report_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabe',
            name='score_report_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabe_loc',
            name='score_report_sent',
            field=models.BooleanField(default=False),
        ),
    ]
