# Generated by Django 4.0.4 on 2022-10-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0040_clas_e_score_report_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas_e',
            name='write_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
        migrations.AddField(
            model_name='clas_e',
            name='write_nrs',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='clas_e',
            name='write_ss',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clas_e',
            name='read_level',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='clas_e',
            name='read_ss',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
