# Generated by Django 4.1.6 on 2023-02-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0041_clas_e_write_level_clas_e_write_nrs_clas_e_write_ss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiset_practice',
            name='test_version',
            field=models.CharField(blank=True, choices=[('FPT2', 'Free Practice Test 2 (2015)'), ('FPT3', 'Free Practice Test 3 (2015)'), ('PPT2', 'Paid Practice Test 2 (2015)'), ('PPT3', 'Paid Practice Test 3 (2015)'), ('PPT4', 'Paid Practice Test 4 (2015)'), ('PPT5', 'Paid Practice Test 5 (2015)'), ('OPT2', 'Official Practice Test 2 (2015)'), ('OPT3', 'Official Practice Test 3 (2015)'), ('FPT6A', 'Free Practice Test 6A (2016)'), ('PPT6A', 'Paid Practice Test 6A (2016)'), ('OPT6A', 'Official Practice Test 6A (2016)'), ('FPT7', 'Free Practice Test 7 (2017)'), ('OPT7', 'Official Practice Test 7 (2017)'), ('OPT8', 'Official Practice Test 8 (2018)'), ('OPT9', 'Official Practice Test 9 (2019)'), ('OPT10', 'Official Practice Test 10 (2020)'), ('OPT11', 'Official Practice Test 11 (2021)'), ('OPT12', 'Official Practice Test 12 (2022)'), ('OPT13', 'Official Practice Test 13 (2023)')], max_length=5),
        ),
    ]
