# Generated by Django 4.1.6 on 2023-03-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0042_alter_hiset_practice_test_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='testevent',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testevent',
            name='test',
            field=models.CharField(choices=[('TABE', 'TABE Test'), ('TABE Locator', 'TABE Locator'), ('CLAS-E', 'CLAS-E Test'), ('CLAS-E Locator', 'CLAS-E Locator'), ('Orientation', 'In Person Program Orientation'), ('Closed Orientaion', 'eOO and ELLOO Google Classroom Orientation'), ('Online Orientation', 'Online Program Orientation'), ('HiSET Practice', 'HiSET Practice'), ('Exit Exam', 'Exit Exam')], max_length=20),
        ),
    ]
