# Generated by Django 4.2.4 on 2023-12-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0043_testevent_hidden_alter_testevent_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='hiset_authorization_form',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
