# Generated by Django 4.2.10 on 2024-08-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0045_testappointment_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testevent',
            name='test',
            field=models.CharField(choices=[('TABE', 'TABE Test'), ('TABE Locator', 'TABE Locator'), ('CLAS-E', 'CLAS-E Test'), ('CLAS-E Locator', 'CLAS-E Locator'), ('Orientation', 'In Person Program Orientation'), ('Closed Orientaion', 'eOO and ELLOO Google Classroom Orientation'), ('Online Orientation', 'Online Program Orientation'), ('Email Update', 'Email Update'), ('HiSET Practice', 'HiSET Practice'), ('Exit Exam', 'Exit Exam')], max_length=20),
        ),
    ]
