# Generated by Django 5.1.2 on 2024-10-29 18:32

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('people', '0001_initial'),
        ('semesters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=60, verbose_name='Street Address')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(default='LA', max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('g_suite_id', models.CharField(blank=True, max_length=20)),
                ('g_suite_link', models.CharField(blank=True, max_length=100)),
                ('room', models.CharField(blank=True, max_length=20)),
                ('program', models.CharField(blank=True, choices=[('ELL', 'ELL'), ('CCR', 'CCR'), ('ADMIN', 'Admin'), ('ELRN', 'eLearn'), ('TRANS', 'Transitions')], max_length=5, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('starting', models.DateField(blank=True, null=True)),
                ('ending', models.DateField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('WRU_ID', models.IntegerField(blank=True, null=True)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('slug', models.CharField(default=core.utils.make_slug, max_length=5, unique=True)),
                ('att_summary', models.BooleanField(default=False)),
                ('att_table', models.BooleanField(default=True)),
                ('import_essential_ed', models.BooleanField(default=False)),
                ('import_duolingo', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.course')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='semesters.semester')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='people.staff')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='sections.site')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=160)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('sections', models.ManyToManyField(to='sections.section')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('W', 'Waitlist'), ('R', 'Withdrawn'), ('D', 'Dropped'), ('C', 'Completed')], default='A', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('schedule_sent', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_records', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_enrollments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='people.student')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='sections.section')),
            ],
            options={
                'unique_together': {('student', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateField()),
                ('notification_sent', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=False)),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='sections.section')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('X', '-----'), ('C', 'Cancelled')], default='X', max_length=1)),
                ('attendance_date', models.DateField()),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('att_hours', models.FloatField(blank=True, null=True)),
                ('online', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=80)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='sections.enrollment')),
            ],
            options={
                'ordering': ['attendance_date'],
                'unique_together': {('enrollment', 'attendance_date', 'att_hours')},
            },
        ),
    ]
