# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='session',
            new_name='semester',
        ),
    ]
