# Generated by Django 5.1.2 on 2025-08-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
