# Generated by Django 5.1.2 on 2025-12-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_attendance_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
