# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_auto_20160917_1435'),
        ('semesters', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='semesters.Semester'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
