# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_auto_20161202_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('X', 'Pending'), ('C', 'Cancelled')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('W', 'Waitlist'), ('R', 'Withdrawn'), ('D', 'Dropped'), ('C', 'Completed')], default='A', max_length=1),
        ),
    ]
