# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0010_section_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('X', 'Pending'), ('C', 'Cancelled')], default='X', max_length=1),
        ),
    ]
