# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0012_auto_20170101_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='site',
            field=models.CharField(blank=True, choices=[('CP', 'City Park'), ('MC', 'NOALC'), ('WB', 'West Bank'), ('JP', 'Jefferson Parish'), ('SC', 'Sidney Collier'), ('HC', 'HCC'), ('WL', 'West Bank Regional Library'), ('J1', 'Job 1')], max_length=2),
        ),
    ]
