# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0013_auto_20170104_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='semesters.Semester'),
        ),
    ]
