# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0014_auto_20170105_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='end_time',
            field=models.TimeField(default=datetime.time(8, 30)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 30)),
            preserve_default=False,
        ),
    ]
