# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0015_auto_20170306_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='program',
            field=models.CharField(blank=True, choices=[('ESL', 'ESL'), ('CCR', 'CCR'), ('ADMIN', 'Admin'), ('ELRN', 'eLearn'), ('TRANS', 'Transitions')], max_length=5, null=True),
        ),
    ]
