# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20171004_1015'),
        ('sections', '0016_auto_20170405_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.Course'),
        ),
        migrations.AddField(
            model_name='section',
            name='g_suite_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='site',
            field=models.CharField(blank=True, choices=[('CP', 'City Park'), ('MC', 'NOALC'), ('WB', 'West Bank'), ('JP', 'Jefferson Parish'), ('SC', 'Sidney Collier'), ('HC', 'HCC'), ('WL', 'West Bank Regional Library'), ('J1', 'Job 1'), ('CH', 'Charity')], max_length=2),
        ),
    ]
