# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-05 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0018_auto_20171101_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='att_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
