# Generated by Django 2.0.7 on 2018-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0022_auto_20181006_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='site',
            field=models.CharField(blank=True, choices=[('CP', 'City Park'), ('MC', 'NOALC'), ('WB', 'West Bank'), ('JP', 'Jefferson Parish'), ('SC', 'Sidney Collier'), ('HC', 'HCC'), ('WL', 'West Bank Regional Library'), ('J1', 'Job 1'), ('CH', 'Charity'), ('OL', 'Online Classes'), ('RC', 'River City')], max_length=2),
        ),
    ]
