# Generated by Django 2.0.7 on 2019-04-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0023_auto_20181008_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=60, verbose_name='Street Address')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(default='LA', max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
    ]
