# Generated by Django 2.0.7 on 2019-06-26 18:47

from django.db import migrations

def get_sites(apps, schema_editor):
	Site = apps.get_model('sections', 'Site')
	Section = apps.get_model('sections', 'Section')
	for section in Section.objects.all():
		section.site_link = Site.objects.get(code=section.site)
		section.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0025_section_site_link'),
    ]

    operations = [
    	migrations.RunPython(get_sites),
    ]
