# Generated by Django 2.0.7 on 2019-06-26 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0027_remove_section_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='site_link',
            new_name='site',
        ),
    ]
