# Generated by Django 2.0.7 on 2019-09-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0028_auto_20190626_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
