# Generated by Django 2.0.7 on 2019-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0029_auto_20190905_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
