# Generated by Django 3.0.14 on 2021-11-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0035_section_g_suite_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='program',
            field=models.CharField(blank=True, choices=[('ELL', 'ELL'), ('CCR', 'CCR'), ('ADMIN', 'Admin'), ('ELRN', 'eLearn'), ('TRANS', 'Transitions')], max_length=5, null=True),
        ),
    ]
