# Generated by Django 4.0.4 on 2022-09-16 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sections', '0038_enrollment_schedule_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateField()),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='sections.section')),
            ],
        ),
    ]
