# Generated by Django 4.0.4 on 2022-09-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0039_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
