# Generated by Django 4.0.4 on 2022-09-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0040_cancellation_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
    ]
