# Generated by Django 4.2.4 on 2023-12-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0043_alter_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
