# Generated by Django 4.2.10 on 2024-03-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0045_enrollment_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='sections.enrollment'),
        ),
    ]
