# Generated by Django 4.2.10 on 2024-04-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0046_alter_attendance_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='att_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='att_table',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='import_duolingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='import_essential_ed',
            field=models.BooleanField(default=False),
        ),
    ]
