# Generated by Django 5.1.2 on 2024-10-29 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.staff'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.student'),
        ),
        migrations.AddField(
            model_name='coursecompletion',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.staff'),
        ),
        migrations.AddField(
            model_name='coursecompletion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.course'),
        ),
        migrations.AddField(
            model_name='coursecompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.student'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.credential'),
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(blank=True, to='academics.resource'),
        ),
        migrations.AddField(
            model_name='skill',
            name='resources',
            field=models.ManyToManyField(blank=True, to='academics.resource'),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, to='academics.skill'),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.staff'),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.skill'),
        ),
        migrations.AddField(
            model_name='skillmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.student'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecompletion',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('student', 'credential')},
        ),
        migrations.AlterUniqueTogether(
            name='skillmastery',
            unique_together={('student', 'skill')},
        ),
    ]
