# Generated by Django 5.1.2 on 2024-12-10 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('people', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certified_%(class)ss', to='people.staff'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='academics.credential'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='people.student'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certified_%(class)ss', to='people.staff'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completions', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='people.student'),
        ),
        migrations.AlterField(
            model_name='skillmastery',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certified_%(class)ss', to='people.staff'),
        ),
        migrations.AlterField(
            model_name='skillmastery',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masteries', to='academics.skill'),
        ),
        migrations.AlterField(
            model_name='skillmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='people.student'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_date', models.DateField()),
                ('certifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certified_%(class)ss', to='people.staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='people.student')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='academics.milestone')),
            ],
            options={
                'ordering': ['milestone'],
                'unique_together': {('student', 'milestone')},
            },
        ),
    ]
