# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20171004_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='objectives',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(blank=True, to='academics.Resource'),
        ),
        migrations.AlterField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, to='academics.Skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='resources',
            field=models.ManyToManyField(blank=True, to='academics.Resource'),
        ),
    ]
