# Generated by Django 2.0.7 on 2019-06-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20171016_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='standard',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='title',
        ),
        migrations.AddField(
            model_name='skill',
            name='anchor_standard',
            field=models.TextField(blank=True),
        ),
    ]
