# Generated by Django 3.0.8 on 2021-01-22 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0062_auto_20201019_2302'),
        ('academics', '0005_certificate_coursecompletion_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='people.Staff'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='people.Student'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coursecompletions', to='people.Staff'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coursecompletions', to='people.Student'),
        ),
    ]
