# Generated by Django 3.0.8 on 2021-02-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0062_auto_20201019_2302'),
        ('academics', '0006_auto_20210122_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_date', models.DateField()),
                ('certifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skillmasterys', to='people.Staff')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.Skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skillmasterys', to='people.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
