# Generated by Django 4.0.4 on 2022-07-12 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0078_auto_20220201_1955'),
        ('academics', '0009_auto_20210308_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.staff'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.student'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.staff'),
        ),
        migrations.AlterField(
            model_name='coursecompletion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.student'),
        ),
        migrations.AlterField(
            model_name='skillmastery',
            name='certifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.staff'),
        ),
        migrations.AlterField(
            model_name='skillmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='people.student'),
        ),
    ]
