# Generated by Django 4.1.6 on 2023-02-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_certificate_certifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nrs_max',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='course',
            name='nrs_min',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
