# Generated by Django 4.1.6 on 2023-07-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_course_nrs_max_course_nrs_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='nrs_type',
            field=models.CharField(blank=True, choices=[('TABE R', 'TABE Reading'), ('TABE M', 'TABE Math'), ('TABE L', 'TABE Language'), ('CLAS-E R', 'CLAS-E Reading')], max_length=10),
        ),
    ]
